# Generated by Django 5.1.7 on 2025-03-27 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='click',
            name='shortener_c_timesta_6bd481_idx',
        ),
        migrations.RemoveIndex(
            model_name='shortenedurl',
            name='shortener_s_short_c_f1ca7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='shortenedurl',
            name='shortener_s_expires_b952e7_idx',
        ),
        migrations.AddField(
            model_name='click',
            name='redirection_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
